### ISSUE TITLE
Client and services are unable to communicate when pinned

### ISSUE THREAD

**Issue by derlarsen** [senecajs/seneca-redis-pubsub-transport#8]
Hi,
in my test setup I have 2 services (Dummy 1 and Dummy 2) which both register with the same Redis queue.

dummy1-service.js:
```Javascript
require('seneca')()
    .use('redis-transport')
    .ready(function() {
        this.add({role: 'Dummy1', cmd: 'hello'}, function (args, callback) {
            return callback(null, {msg: 'Hello, this is Dummy1'});
        });
    })
    .listen({type:'redis', pin:'role:Dummy1,cmd:*'});
```

dummy2-service.js:
```Javascript
require('seneca')()
    .use('redis-transport')
    .ready(function() {
        this.add({role: 'Dummy2', cmd: 'hello'}, function (args, callback) {
            return callback(null, {msg: 'Hello, this is Dummy2'});
        });
    })
    .listen({type:'redis', pin:'role:Dummy2,cmd:*'});
```
Both services are running.

Now with my test script that look like the following:
```Javascript
require('seneca')()
    .use('redis-transport')
    .client({type:'redis'})
    .ready(function () {
        this.act('role:Dummy1,cmd:hello', function (err, result) {
            if (err) throw err;
            console.log('Dummy 1 result:', result);
        });

        this.act('role:Dummy2,cmd:hello', function (err, result) {
            if (err) throw err;
            console.log('Dummy 2 result:', result);
        });

    });
```

I don't receive any response, the request times out and throws an error.

Checking the Redis pubsub, I see that there are 2 active channels:
```
127.0.0.1:6379> PUBSUB CHANNELS
1) "seneca_cmd_hello_role_Dummy1__act"
2) "seneca_cmd_hello_role_Dummy2__act"
```
Looks ok so far.

The problem seems to be that the client publishes on "seneca_any_act" and hence isn't recognized by the services. Am I doing something wrong here? Shouldn't the client publish on channels that the services are subscribed to?

Best
Lars

**Comment by anshulAtStack** [comment]
You have to provide pin on the client side too.

In your test script `->`  .client({type:'redis',pin:(Your pin here)})

**Comment by Mohamed-Habshey** [comment]
Hi @derlarsen 

i was facing the same problem as yours but i believe as defined in this redis PUB/SUB 

> "Note: This is broadcast transport. All subscribed micro-services receive all messages." 

so i think the convenient approach is to **neither use pin/s in client nor listen** as all micro-services will receive all messages, so instead use pattern matching.

Regards
M.Habashy

**Comment by dgonzalez** [comment]
This is related to: https://github.com/senecajs/seneca-redis-pubsub-transport/issues/34. I am aggregating all the issues in there.

Please follow up in there and feel free to re-open if the answer does not fit your needs!
